"""Render ref-impact results as a table and refresh docs/benchmark/latest.md.

Usage: ``imv-bench report <results_root>`` (or ``python report.py``).
Reads every ``results/*_<condition>/`` run with a summary.json, prints a
per-run table plus per-condition mean/min/max, and rewrites latest.md
from the same numbers — the doc never contains anything the logs don't.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))


def load_runs(results_root: Path) -> list[dict]:
    runs = []
    for run_dir in sorted(results_root.iterdir()):
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / "summary.json"
        env_path = run_dir / "env.json"
        if not (summary_path.exists() and env_path.exists()):
            continue
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
        env = json.loads(env_path.read_text(encoding="utf-8"))
        runs.append({"dir": run_dir.name, **summary, **{
            k: env.get(k) for k in ("condition", "model_adapter",
                                    "model_ref", "imv_version",
                                    "git_commit", "status")}})
    return runs


def fmt_pct(value) -> str:
    return f"{100 * value:.1f} %" if value is not None else "–"


def render_table(runs: list[dict]) -> str:
    lines = ["| run | recall (30) | leak | tool calls/q | median ms | failed |",
             "|---|---|---|---|---|---|"]
    for r in runs:
        lines.append(
            f"| {r['dir']} | {fmt_pct(r['recall'])} | "
            f"{fmt_pct(r['leak_rate'])} | {r['tool_calls_per_q']:.1f} | "
            f"{r['median_latency_ms']} | {r['failed']} |")
    by_cond: dict[str, list[dict]] = defaultdict(list)
    for r in runs:
        by_cond[r.get("condition", "?")].append(r)
    lines += ["", "| condition | recall mean (min–max) | leak mean | runs |",
              "|---|---|---|---|"]
    for cond in sorted(by_cond):
        group = by_cond[cond]
        recalls = [g["recall"] for g in group if g["recall"] is not None]
        leaks = [g["leak_rate"] for g in group if g["leak_rate"] is not None]
        rmean = sum(recalls) / len(recalls) if recalls else None
        lmean = sum(leaks) / len(leaks) if leaks else None
        span = (f"{100 * min(recalls):.1f}–{100 * max(recalls):.1f} %"
                if recalls else "–")
        lines.append(f"| {cond} | "
                     f"{fmt_pct(rmean)} ({span}) | {fmt_pct(lmean)} | "
                     f"{len(group)} |")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(prog="imv-bench report")
    parser.add_argument("results_root", nargs="?",
                        default="bench/ref_impact/results")
    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parents[2]
    root = Path(args.results_root)
    if not root.is_absolute():
        root = repo_root / root
    runs = load_runs(root)
    if not runs:
        raise SystemExit(f"no completed runs in {root}")
    table = render_table(runs)
    latest = repo_root / "docs" / "benchmark" / "latest.md"
    latest.parent.mkdir(parents=True, exist_ok=True)
    latest.write_text(
        "# ref-impact latest results\n\n"
        "Generated by `imv-bench report` from the raw logs in\n"
        "`bench/ref_impact/results/`. Numbers here never diverge from "
        "those logs.\n\n" + table + "\n",
        encoding="utf-8")
    print(f"wrote {latest}")
    print(table.encode("ascii", errors="replace").decode("ascii"))


if __name__ == "__main__":
    main()
